spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: { 200MB }
      max-request-size: 215MB

server:
  port: 8080

security:
  jwt:
    secret: ${SECRET_KEY}
    accessTokenExpirationMs: 3600000
    refreshTokenExpirationMs: 86400000


file:
  image-project: /images/projects
  image-user-avatar: /images/avatars

cors:
  originPatterns: ${ORIGINS}

app:
  base:
    path: { URL_APP:http://localhost:8080/ }