spring:
  application:
    name: kyw_project

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/KYW_PROJECT
    username: MASTER
    password: SECRETPASSWORD
  neo4j:
    security:
      hostname-verification-enabled: off
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8080


