name: Continuous Integration with GitHub Actions

on:
  push:
    branches:
        - "main"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
   
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Application jar
      working-directory: ./
      run: mvn package

    - name: Docker Compose Build
      working-directory: ./backend
      run: docker compose build

    - name: Push to Docker Hub Container Registry
      run: |
        docker tag  docker.io/${{ secrets.DOCKER_USERNAME }}/kyw:latest ${{ secrets.DOCKER_USERNAME }}/kyw:${{ github.run_id }}
        
        docker push ${{ secrets.DOCKER_USERNAME }}/kyw:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/kyw:latest
